# Generated by Django 4.0.6 on 2022-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
