# Generated by Django 4.0.6 on 2022-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_shopcart_c_date_alter_payment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='c_item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='c_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
