# Generated by Django 4.0.6 on 2022-08-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'managed': True, 'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
