# Generated by Django 4.0.6 on 2022-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0005_rename_cereal_dish_appetizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(),
        ),
    ]
