# Generated by Django 4.0.6 on 2022-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0007_dish_special_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_image', models.ImageField(upload_to='showimage')),
            ],
        ),
    ]
