# Generated by Django 4.0.6 on 2022-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0009_showcase_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='showsub_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
